### ISSUE TITLE
AttributeError: module 'paddle' has no attribute '__version__'

### ISSUE THREAD

**Issue by HuangXinzhe** [PaddlePaddle/PaddleFormers#2254]
欢迎您反馈PaddleHub使用问题，非常感谢您对PaddleHub的贡献！
在留下您的问题时，辛苦您同步提供如下信息：
- 版本、环境信息
1）PaddleHub和PaddlePaddle版本：请提供您的PaddleHub和PaddlePaddle版本号，例如PaddleHub1.4.1，PaddlePaddle1.6.2
2）系统环境：请您描述系统类型，例如Linux/Windows/MacOS/，python版本
- 复现信息：如为报错，请给出复现环境、复现步骤

**Comment by HuangXinzhe** [comment]
- 版本、环境信息
paddlehub                   2.3.1
paddlepaddle                2.3.0
MacOS
- 运行代码
```python
import paddlehub as hub

lac = hub.Module(name="lac")
test_text = ["今天是个好天气。"]

results = lac.cut(text=test_text, use_gpu=False, batch_size=1, return_tag=True)
print(results)
#{'word': ['今天', '是', '个', '好天气', '。'], 'tag': ['TIME', 'v', 'q', 'n', 'w']}
```
- 报错
Traceback (most recent call last):
  File "/Users/huangxinzhe/code/common_tools/paddle/test.py", line 1, in <module>
    import paddlehub as hub
  File "/Users/huangxinzhe/opt/anaconda3/envs/common9/lib/python3.9/site-packages/paddlehub/__init__.py", line 20, in <module>
    _paddle_version = Version(paddle.__version__)
AttributeError: module 'paddle' has no attribute '__version__'

**Comment by dineshresearch** [comment]
@HuangXinzhe I am also facing the same error. Did you found any fix / resolution?

**Comment by HuangXinzhe** [comment]
For my question, this is not a question of paddle，because there was a folder named by paddle in the directory of my code

**Comment by HuangXinzhe** [comment]
> @HuangXinzhe I am also facing the same error. Did you found any fix / resolution?


For my question, this is not a question of paddle，because there was a folder named by paddle in the directory of my code.

**Comment by Haeppypuppy** [comment]
I still face the question now, how should i fix it.
I am not sure if the problem is paddle version release or not

<import paddlehub as hub>
<AttributeError                            Traceback (most recent call last)
[<ipython-input-47-e6d9344ab8a2>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import paddlehub as hub

8 frames
[/usr/local/lib/python3.10/dist-packages/paddlenlp/transformers/ernie_ctm/modeling.py](https://localhost:8080/#) in <module>
     33 )
     34 
---> 35 if compare_version(paddle.version.full_version, "2.2.0") >= 0:
     36     # paddle.text.ViterbiDecoder is supported by paddle after version 2.2.0
     37     from paddle.text import ViterbiDecoder

AttributeError: module 'paddle' has no attribute 'version'

>
